// Generated by gencpp from file y1_msg/ArmEndPoseControl.msg
// DO NOT EDIT!


#ifndef Y1_MSG_MESSAGE_ARMENDPOSECONTROL_H
#define Y1_MSG_MESSAGE_ARMENDPOSECONTROL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace y1_msg
{
template <class ContainerAllocator>
struct ArmEndPoseControl_
{
  typedef ArmEndPoseControl_<ContainerAllocator> Type;

  ArmEndPoseControl_()
    : header()
    , end_pose()
    , joint_velocity(0)
    , gripper_stroke(0.0)
    , gripper_velocity(0)  {
      end_pose.assign(0.0);
  }
  ArmEndPoseControl_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , end_pose()
    , joint_velocity(0)
    , gripper_stroke(0.0)
    , gripper_velocity(0)  {
  (void)_alloc;
      end_pose.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 6>  _end_pose_type;
  _end_pose_type end_pose;

   typedef uint8_t _joint_velocity_type;
  _joint_velocity_type joint_velocity;

   typedef double _gripper_stroke_type;
  _gripper_stroke_type gripper_stroke;

   typedef uint8_t _gripper_velocity_type;
  _gripper_velocity_type gripper_velocity;





  typedef boost::shared_ptr< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> const> ConstPtr;

}; // struct ArmEndPoseControl_

typedef ::y1_msg::ArmEndPoseControl_<std::allocator<void> > ArmEndPoseControl;

typedef boost::shared_ptr< ::y1_msg::ArmEndPoseControl > ArmEndPoseControlPtr;
typedef boost::shared_ptr< ::y1_msg::ArmEndPoseControl const> ArmEndPoseControlConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::y1_msg::ArmEndPoseControl_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::y1_msg::ArmEndPoseControl_<ContainerAllocator1> & lhs, const ::y1_msg::ArmEndPoseControl_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.end_pose == rhs.end_pose &&
    lhs.joint_velocity == rhs.joint_velocity &&
    lhs.gripper_stroke == rhs.gripper_stroke &&
    lhs.gripper_velocity == rhs.gripper_velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::y1_msg::ArmEndPoseControl_<ContainerAllocator1> & lhs, const ::y1_msg::ArmEndPoseControl_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace y1_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "142e2b7c756c7198bc7edcbeeeaba6ed";
  }

  static const char* value(const ::y1_msg::ArmEndPoseControl_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x142e2b7c756c7198ULL;
  static const uint64_t static_value2 = 0xbc7edcbeeeaba6edULL;
};

template<class ContainerAllocator>
struct DataType< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "y1_msg/ArmEndPoseControl";
  }

  static const char* value(const ::y1_msg::ArmEndPoseControl_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# x y z roll pitch yaw\n"
"float64[6] end_pose\n"
"\n"
"# range: [1, 10], 1 is slow, 10 is fast\n"
"uint8 joint_velocity\n"
"\n"
"# individual gripper control\n"
"float64 gripper_stroke\n"
"\n"
"# range: [1, 10], 1 is slow, 10 is fast\n"
"uint8 gripper_velocity\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::y1_msg::ArmEndPoseControl_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.end_pose);
      stream.next(m.joint_velocity);
      stream.next(m.gripper_stroke);
      stream.next(m.gripper_velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmEndPoseControl_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::y1_msg::ArmEndPoseControl_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::y1_msg::ArmEndPoseControl_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "end_pose[]" << std::endl;
    for (size_t i = 0; i < v.end_pose.size(); ++i)
    {
      s << indent << "  end_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_pose[i]);
    }
    s << indent << "joint_velocity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.joint_velocity);
    s << indent << "gripper_stroke: ";
    Printer<double>::stream(s, indent + "  ", v.gripper_stroke);
    s << indent << "gripper_velocity: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gripper_velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // Y1_MSG_MESSAGE_ARMENDPOSECONTROL_H
