// Generated by gencpp from file y1_msg/ArmJointState.msg
// DO NOT EDIT!


#ifndef Y1_MSG_MESSAGE_ARMJOINTSTATE_H
#define Y1_MSG_MESSAGE_ARMJOINTSTATE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace y1_msg
{
template <class ContainerAllocator>
struct ArmJointState_
{
  typedef ArmJointState_<ContainerAllocator> Type;

  ArmJointState_()
    : header()
    , end_pose()
    , joint_position()
    , joint_velocity()
    , joint_effort()  {
      end_pose.assign(0.0);
  }
  ArmJointState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , end_pose()
    , joint_position(_alloc)
    , joint_velocity(_alloc)
    , joint_effort(_alloc)  {
  (void)_alloc;
      end_pose.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef boost::array<double, 6>  _end_pose_type;
  _end_pose_type end_pose;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_position_type;
  _joint_position_type joint_position;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_velocity_type;
  _joint_velocity_type joint_velocity;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_effort_type;
  _joint_effort_type joint_effort;





  typedef boost::shared_ptr< ::y1_msg::ArmJointState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::y1_msg::ArmJointState_<ContainerAllocator> const> ConstPtr;

}; // struct ArmJointState_

typedef ::y1_msg::ArmJointState_<std::allocator<void> > ArmJointState;

typedef boost::shared_ptr< ::y1_msg::ArmJointState > ArmJointStatePtr;
typedef boost::shared_ptr< ::y1_msg::ArmJointState const> ArmJointStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::y1_msg::ArmJointState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::y1_msg::ArmJointState_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::y1_msg::ArmJointState_<ContainerAllocator1> & lhs, const ::y1_msg::ArmJointState_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.end_pose == rhs.end_pose &&
    lhs.joint_position == rhs.joint_position &&
    lhs.joint_velocity == rhs.joint_velocity &&
    lhs.joint_effort == rhs.joint_effort;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::y1_msg::ArmJointState_<ContainerAllocator1> & lhs, const ::y1_msg::ArmJointState_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace y1_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmJointState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmJointState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmJointState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmJointState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmJointState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::y1_msg::ArmJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "303651795b96b734ba0e948b824c3d6f";
  }

  static const char* value(const ::y1_msg::ArmJointState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x303651795b96b734ULL;
  static const uint64_t static_value2 = 0xba0e948b824c3d6fULL;
};

template<class ContainerAllocator>
struct DataType< ::y1_msg::ArmJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "y1_msg/ArmJointState";
  }

  static const char* value(const ::y1_msg::ArmJointState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::y1_msg::ArmJointState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# x y z roll pitch yaw\n"
"float64[6] end_pose\n"
"\n"
"# joint position information\n"
"float64[] joint_position\n"
"\n"
"# joint velocity information\n"
"float64[] joint_velocity\n"
"\n"
"# joint effort information\n"
"float64[] joint_effort\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::y1_msg::ArmJointState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::y1_msg::ArmJointState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.end_pose);
      stream.next(m.joint_position);
      stream.next(m.joint_velocity);
      stream.next(m.joint_effort);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmJointState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::y1_msg::ArmJointState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::y1_msg::ArmJointState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "end_pose[]" << std::endl;
    for (size_t i = 0; i < v.end_pose.size(); ++i)
    {
      s << indent << "  end_pose[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.end_pose[i]);
    }
    s << indent << "joint_position[]" << std::endl;
    for (size_t i = 0; i < v.joint_position.size(); ++i)
    {
      s << indent << "  joint_position[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_position[i]);
    }
    s << indent << "joint_velocity[]" << std::endl;
    for (size_t i = 0; i < v.joint_velocity.size(); ++i)
    {
      s << indent << "  joint_velocity[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_velocity[i]);
    }
    s << indent << "joint_effort[]" << std::endl;
    for (size_t i = 0; i < v.joint_effort.size(); ++i)
    {
      s << indent << "  joint_effort[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.joint_effort[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // Y1_MSG_MESSAGE_ARMJOINTSTATE_H
