// Generated by gencpp from file y1_msg/ArmStatus.msg
// DO NOT EDIT!


#ifndef Y1_MSG_MESSAGE_ARMSTATUS_H
#define Y1_MSG_MESSAGE_ARMSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <std_msgs/String.h>

namespace y1_msg
{
template <class ContainerAllocator>
struct ArmStatus_
{
  typedef ArmStatus_<ContainerAllocator> Type;

  ArmStatus_()
    : header()
    , name()
    , error_code()
    , rotor_temperature()
    , motor_current()  {
    }
  ArmStatus_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , name(_alloc)
    , error_code(_alloc)
    , rotor_temperature(_alloc)
    , motor_current(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::std_msgs::String_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::std_msgs::String_<ContainerAllocator> >> _name_type;
  _name_type name;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _error_code_type;
  _error_code_type error_code;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _rotor_temperature_type;
  _rotor_temperature_type rotor_temperature;

   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _motor_current_type;
  _motor_current_type motor_current;





  typedef boost::shared_ptr< ::y1_msg::ArmStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::y1_msg::ArmStatus_<ContainerAllocator> const> ConstPtr;

}; // struct ArmStatus_

typedef ::y1_msg::ArmStatus_<std::allocator<void> > ArmStatus;

typedef boost::shared_ptr< ::y1_msg::ArmStatus > ArmStatusPtr;
typedef boost::shared_ptr< ::y1_msg::ArmStatus const> ArmStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::y1_msg::ArmStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::y1_msg::ArmStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::y1_msg::ArmStatus_<ContainerAllocator1> & lhs, const ::y1_msg::ArmStatus_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.name == rhs.name &&
    lhs.error_code == rhs.error_code &&
    lhs.rotor_temperature == rhs.rotor_temperature &&
    lhs.motor_current == rhs.motor_current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::y1_msg::ArmStatus_<ContainerAllocator1> & lhs, const ::y1_msg::ArmStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace y1_msg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::y1_msg::ArmStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::y1_msg::ArmStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::y1_msg::ArmStatus_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::y1_msg::ArmStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9bd0b4838b8ed632646459a083d5c41d";
  }

  static const char* value(const ::y1_msg::ArmStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9bd0b4838b8ed632ULL;
  static const uint64_t static_value2 = 0x646459a083d5c41dULL;
};

template<class ContainerAllocator>
struct DataType< ::y1_msg::ArmStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "y1_msg/ArmStatus";
  }

  static const char* value(const ::y1_msg::ArmStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::y1_msg::ArmStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"\n"
"# joint names\n"
"std_msgs/String[] name\n"
"\n"
"# joint error codes \n"
"uint8[] error_code\n"
"\n"
"# motor internal coil temperature\n"
"float32[] rotor_temperature\n"
"\n"
"# joint motor current\n"
"float32[] motor_current\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::y1_msg::ArmStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::y1_msg::ArmStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.name);
      stream.next(m.error_code);
      stream.next(m.rotor_temperature);
      stream.next(m.motor_current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ArmStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::y1_msg::ArmStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::y1_msg::ArmStatus_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "name[]" << std::endl;
    for (size_t i = 0; i < v.name.size(); ++i)
    {
      s << indent << "  name[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "    ", v.name[i]);
    }
    s << indent << "error_code[]" << std::endl;
    for (size_t i = 0; i < v.error_code.size(); ++i)
    {
      s << indent << "  error_code[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.error_code[i]);
    }
    s << indent << "rotor_temperature[]" << std::endl;
    for (size_t i = 0; i < v.rotor_temperature.size(); ++i)
    {
      s << indent << "  rotor_temperature[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.rotor_temperature[i]);
    }
    s << indent << "motor_current[]" << std::endl;
    for (size_t i = 0; i < v.motor_current.size(); ++i)
    {
      s << indent << "  motor_current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.motor_current[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // Y1_MSG_MESSAGE_ARMSTATUS_H
